### ISSUE TITLE
Function to extract texture features 

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#1350]
### Description
`sct_analyze_texture`
This function will extract texture features from an image within a given mask (for example within SC segmentation or within lesions, ...). It will use the extraction of textures from sckit-image: http://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.greycomatrix

### Output 
Output will be a nifti file per texture metric. Metrics are:

- contrast
- dissimilarity
- homogeneity
- ASM
- energy
- correlation

### Usage
`sct_analyze_texture -i image.nii.gz -s segmentation.nii.gz -ofolder output_folder -param ` 

### Additional information
The outputs (texture maps) could be used in `sct_extract_metric` to extract the texture features in specific tracts/regions and/or by slice and vertebral levels. 
 `sct_extract_metric` could also be used to extract the textures features from a given mask (other than the atlas)

**Comment by charleygros** [comment]
## **Usage:**
```
DESCRIPTION
Extraction of GLCM texture features from an image within a given mask.
   It calculates the texture properties of a grey level co-occurence matrix (GLCM). The textures 
    features are those defined in the sckit-image implementation:
   http://scikit-image.org/docs/dev/api/skimage.feature.html#greycoprops
   This function outputs one nifti file per texture metric (contrast, dissimilarity, homogeneity, 
    ASM, energy, correlation) and per orientation called fnameIn_property_distance_angle.nii.gz, in 
    the folder ./texture/

USAGE
sct_analyse_texture -i <file> -s <file>

MANDATORY ARGUMENTS
 -i <file>                    Image to analyse              
 -s <file>                    Image mask                    

OPTIONAL ARGUMENTS
 -param <str>                 Parameters for extraction. Separate arguments with ":".
                                prop: <list_str> list of GLCM texture properties: 
                                  contrast,dissimilarity,homogeneity,energy,correlation,ASM.
                                 Default=contrast,dissimilarity,homogeneity,energy,correlation,ASM
                                distance: <int> distance offset in pixel (suggested distance values 
                                  between 1 and 5).
                                 Default=1
                                angle: <list_int> list of angles in degrees (suggested distance 
                                  values between 0 and 179).
                                 Default=0,45,90,135
                                
 -mean {0,1}                  1: Output a file averaging each metric across the angles
 -dim {ax,sag,cor}            Compute the texture on the axial (ax), sagittal (sag) or coronal 
                              (cor) slices. Default value = ax
 -ofolder <folder_creation>   Output folder Default value = ./texture/
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   Verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1
```

## Outputs:
One nifiti file per {metric, angle} called fnameIn_metric_distance_angle.nii.gz (eg. t2_energy_1_0.nii.gz, t2_energy_1_90.nii.gz, t2_asm_1_0.nii.gz, t2_asm_1_90.nii.gz).

Additionnal file per metric (if -mean is 1): mean across angles (eg. t2_energy_1_mean.nii.gz, t2_asm_1_mean.nii.gz).

## Terminal output:
```
python sct_analyse_texture.py -i /Users/chgroc/data/i1350/AIL/t2_sag_cerv.nii.gz -s /Users/chgroc/data/i1350/AIL/t2_sag_cerv_seg_manual.nii.gz -ofolder /Users/chgroc/data/i1350/AIL/texture/ -param prop=contrast:angle=0,45 -dim sag
Check folder existence...
/Users/chgroc/data/i1350/AIL/t2_sag_cerv.nii.gz

Create temporary folder...

Compute texture metrics...
Remaining time: 00:00:00.00 (15/15)                      Total time: 00:00:47.91                      

Mean across angles...
sct_image -i t2_sag_cerv_contrast_1_0.nii.gz,t2_sag_cerv_contrast_1_45.nii.gz -concat t -o t2_sag_cerv_contrast_mean.nii.gz
sct_maths -i t2_sag_cerv_contrast_mean.nii.gz -mean t -o t2_sag_cerv_contrast_mean.nii.gz

Save resulting files...

Done! To view results, type:
fslview /Users/chgroc/data/i1350/AIL/t2_sag_cerv.nii.gz /Users/chgroc/data/i1350/AIL/texture/t2_sag_cerv_contrast_1_45.nii.gz -l Red-Yellow -t 0.7 /Users/chgroc/data/i1350/AIL/texture/t2_sag_cerv_contrast_1_0.nii.gz -l Red-Yellow -t 0.7 /Users/chgroc/data/i1350/AIL/texture/t2_sag_cerv_contrast_mean.nii.gz -l Red-Yellow -t 0.7 & 
```

## Examples:
### Analysis on axial slices:
![screen shot 2017-06-16 at 4 04 35 pm](https://user-images.githubusercontent.com/14353425/27243085-43870f50-52ae-11e7-8989-24ace3fefde9.png)

### Analysis on sagittal slices:
![screen shot 2017-06-16 at 4 07 28 pm](https://user-images.githubusercontent.com/14353425/27243079-397ae5fe-52ae-11e7-849f-8450b10b9de9.png)


## TODO:

- [ ] Use a crop around the mask to speed up

Any comments/suggestion?

(Merci à Sara et Pascale pour leur aide précieuse!)

**Comment by jcohenadad** [comment]
fantastic!!!  i would just replace sct_analyse_texture with sct_analyze_texture (US convention used in SCT).
thank you!

**Comment by charleygros** [comment]
Done:

1. `sct_analyse_texture` --> `sct_analyze_texture`
2. Improved computation time
3. Test `sct_extract_metric` on it:
```
sct_register_to_template.py -i t2_ax.nii.gz -s t2_ax_seg_manual.nii.gz -l labels.nii.gz
sct_warp_template.py -d t2_ax.nii.gz -w warp_template2anat.nii.gz
sct_extract_metric -i texture/t2_ax_contrast_1_mean.nii.gz
```
-->
```
# Combined labels
50, spinal cord, 6536.045098, 367.149821, 132.563301
51, white matter, 5069.096117, 369.624425, 141.648517
52, gray matter, 1466.948981, 358.598739, 94.180994
53, dorsal columns, 2018.237056, 352.254004, 73.710720
54, lateral funiculi, 2491.396922, 361.395874, 141.898669
55, ventral funiculi, 559.462139, 468.930900, 247.542948
...
```

Meeting with George on Monday for review

**Comment by jcohenadad** [comment]
could you please also add a test for this function? You can get inspiration from test_sct_propseg, test_sct_label_vertebral, test_sct_register_multimodal or test_sct_register_to_template
thank you!

**Comment by charleygros** [comment]
- [ ] new function: testing/test_sct_analyze_texture.py
- [ ] test_sct_analyze_texture added to scripts/sct_testing.py
- [ ] add t2_contrast_1_mean_ref.nii.gz to scripts/sct_testing_data/t2/

**Comment by charleygros** [comment]
Changes (related to discussions during sct_meeting):
- Flag names
- `-param` --> `-distance` + `-angle` + `feature`
- output *_mean by default
- Usage reformulation
