### ISSUE TITLE
Implement QC for dmri_moco and fmri_moco

### ISSUE THREAD

**Issue by claragiroux** [neuropoly/spinalcordtoolbox#3242]
Addressing issue #1343 to introduce QC reports for `sct_fmri_moco `and `sct_dmri_moco`:

The report could display GIF images before and after motion correction in an axial mosaic which loops across the 4th dimension (time), as well as a graphic for motion correction parameters.

Mandatory input:
- fname_in1, 4D image after motion correction 

Optional inputs:
- fname_in2, 4D image after motion correction
- fname_seg, segmentation of input image used for cropping
- fps, frame rate for output gif images
- moco_params, TSV file with X and Y motion correction parameters

**Tasks:**
- [x] Introduce new parameter -qc to `sct_qc `for `sct_fmri_moco `and `sct_dmri_moco` #3274
- [x] Create entry in `sct_qc ` and `generate_qc ` for `sct_fmri_moco `and `sct_dmri_moco` 
- [x] Add the function `mosaic_through_time ` in the `Slice `class that will create an axial mosaic for each volume of the input images.
- [x] Add functionnality in `qc.py` to save list of png mosaic files ordered by time.
- [x] Add function in `qc.py ` to generate animated GIF image from the list of png mosaics.
- [x] Add function for white grid overlay in `qc.py `to aid visualization of motion correction.
- [x] Add possibility to crop images to focus on the spinal cord by calculating center of mass (using spinal cord segmentation if provided).
- [ ] Add function to generate moco_params graphic and save as png.
- [ ] Adapt QC report layout to include GIF images and to be able to display up to 3 figures, as shown in preview bellow.

**Proposed layout:**
Mosaics loop through time in GIF format. Overlay is white grid to facilitate visualization.
![apercu_moco_qc](https://user-images.githubusercontent.com/56138625/108788525-2ee74100-7546-11eb-80cf-1fc46caa3c51.png)
